# -*- coding: utf-8 -*-
"""AO Posters_PROD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TuNQPUVOhXuwfHLTFgidnJvhFiO5wzqk
"""

!pip -q install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

from google.colab import auth
auth.authenticate_user()

import google.auth
creds, _ = google.auth.default(scopes=[
    "https://www.googleapis.com/auth/spreadsheets.readonly",
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/presentations",
])

SHEET_ID = "177cdPCpdr_JqJKbnfWm2XTMpquaHAuCuVBYOQwmhHoA"        # <-- spreadsheet ID (not tab name)
SHEET_NAME = "Schedule"

TEMPLATE_PRESENTATION_ID = "1X6gL6Rc85ahMphqu2gltglNT-5hF6yfdEaklRSUkt0E"
TEMPLATE_PRESENTATION_ID = "1i849HBqAfofccS5mfiCt6MHEHbe2UGc3Cyh_3kq6Svo"  #new template
OUTPUT_FOLDER_ID = "1XsAdFZy0TKZQTomynkm7igcY5wg7_RN7"

import re
import datetime as dt
from zoneinfo import ZoneInfo
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaInMemoryUpload
import requests
import logging
from PIL import Image as PILImage
import io
# from IPython.display import Image, display # Removed as user doesn't need direct display for JPEG

# Suppress the specific httplib2 warning
logging.getLogger('google_auth_httplib2').setLevel(logging.ERROR)

LOCAL_TZ = ZoneInfo("America/New_York")

sheets_svc = build("sheets", "v4", credentials=creds)
drive_svc  = build("drive", "v3", credentials=creds)
slides_svc = build("slides", "v1", credentials=creds)

REQUIRED_HEADERS = [
    "Week", "Teams", "Line", "Team-1 Players", "Team-2 Players",
    "Status", "Match Date", "Match Time", "Venue", "Address"
]

def split_teams(cell_value):
    if not cell_value:
        return "", ""
    parts = re.split(r"\s*vs\s*", str(cell_value), flags=re.IGNORECASE)
    return (parts[0].strip() if len(parts) > 0 else "",
            parts[1].strip() if len(parts) > 1 else "")

def split_players(cell_value):
    if not cell_value:
        return "", ""
    parts = str(cell_value).split("&")
    return (parts[0].strip() if len(parts) > 0 else "",
            parts[1].strip() if len(parts) > 1 else "")

def day_suffix(d):
    if 11 <= d % 100 <= 13:
        return "th"
    return {1: "st", 2: "nd", 3: "rd"}.get(d % 10, "th")

def normalize_date_yyyy_mm_dd(date_str):
    if not date_str:
        return ""
    date_str = str(date_str).strip()
    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%m/%d/%y", "%d/%m/%Y"):
        try:
            d = dt.datetime.strptime(date_str, fmt).date()
            return d.strftime("%Y-%m-%d")
        except:
            pass
    if len(date_str) >= 10 and re.match(r"\d{4}-\d{2}-\d{2}", date_str[:10]):
        return date_str[:10]
    return date_str[:10] if len(date_str) >= 10 else date_str

def format_datetime_for_poster(date_str, time_str):
    if not date_str:
        return ""
    date_str = str(date_str).strip()
    parsed_date = None
    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%m/%d/%y", "%d/%m/%Y"):
        try:
            parsed_date = dt.datetime.strptime(date_str, fmt).date()
            break
        except:
            pass
    if parsed_date is None:
        return ""

    day_name = parsed_date.strftime("%A") # Changed to full day name
    d = parsed_date.day
    month_full = parsed_date.strftime("%B") # Changed to full month name
    suffix = day_suffix(d)

    t_out = ""
    if time_str:
        ts = str(time_str).strip().upper().replace(".", "")
        parsed_time = None
        for tfmt in ("%I:%M %p", "%I %p", "%H:%M"):
            try:
                parsed_time = dt.datetime.strptime(ts, tfmt).time()
                break
            except:
                pass

        if parsed_time:
            if parsed_time.minute == 0:
                t_out = parsed_time.strftime("%-I %p")
            else:
                t_out = parsed_time.strftime("%-I:%M %p")
        else:
            t_out = ts.lstrip("0").replace(":00", "") # Fallback if no format matched or for custom strings

    return f"{day_name} - {month_full} {d}{suffix} | {t_out}".strip()

def fetch_sheet_values(spreadsheet_id, sheet_name):
    rng = f"'{sheet_name}'!A:Z"
    resp = sheets_svc.spreadsheets().values().get(
        spreadsheetId=spreadsheet_id,
        range=rng,
        valueRenderOption="FORMATTED_VALUE"
    ).execute()
    return resp.get("values", [])

def get_matches(spreadsheet_id, sheet_name):
    data = fetch_sheet_values(spreadsheet_id, sheet_name)
    if len(data) < 2:
        return []

    headers = data[0]
    idx = {h: headers.index(h) for h in headers}
    missing = [h for h in REQUIRED_HEADERS if h not in idx]
    if missing:
        raise ValueError(f"Missing required headers: {missing}")

    matches = []
    for r in range(1, len(data)):
        row = data[r] + [""] * (len(headers) - len(data[r]))  # pad
        if "".join(str(x) for x in row).strip() == "":
            continue

        teamAName, teamBName = split_teams(row[idx["Teams"]])
        teamAPlayer1, teamAPlayer2 = split_players(row[idx["Team-1 Players"]])
        teamBPlayer1, teamBPlayer2 = split_players(row[idx["Team-2 Players"]])

        date_value = row[idx["Match Date"]]
        time_value = row[idx["Match Time"]]

        matchDate = normalize_date_yyyy_mm_dd(date_value)
        formattedDateTime = format_datetime_for_poster(date_value, time_value)

        matches.append({
            "week": row[idx["Week"]],
            "line": row[idx["Line"]],
            "teamAName": teamAName,
            "teamBName": teamBName,
            "teamAPlayer1": teamAPlayer1,
            "teamAPlayer2": teamAPlayer2,
            "teamBPlayer1": teamBPlayer1,
            "teamBPlayer2": teamBPlayer2,
            "status": row[idx["Status"]],
            "matchDate": matchDate,
            "formattedDateTime": formattedDateTime,
            "venue": row[idx["Venue"]],
            "address": row[idx["Address"]],
        })
    return matches

def get_upcoming_matches(matches, target_date_str=None):
    if target_date_str is None:
        # Get today's date in the correct timezone for comparison
        today_dt = dt.datetime.now(LOCAL_TZ).date()
        today_str = today_dt.strftime("%Y-%m-%d")
    else:
        today_str = target_date_str

    # Filter matches where matchDate is greater than or equal to today_str
    return [m for m in matches if m.get("matchDate") and m.get("matchDate") >= today_str]

def copy_drive_file(file_id, new_name, parent_folder_id):
    body = {"name": new_name, "parents": [parent_folder_id]}
    copied = drive_svc.files().copy(fileId=file_id, body=body).execute()
    return copied["id"]

def batch_replace_text(presentation_id, replacements):
    requests_body = []
    for find_text, replace_text in replacements.items():
        requests_body.append({
            "replaceAllText": {
                "containsText": {"text": find_text, "matchCase": True},
                "replaceText": replace_text or ""
            }
        })
    slides_svc.presentations().batchUpdate(
        presentationId=presentation_id,
        body={"requests": requests_body}
    ).execute()

def get_first_slide_object_id(presentation_id):
    pres = slides_svc.presentations().get(presentationId=presentation_id).execute()
    slides = pres.get("slides", [])
    if not slides:
        raise ValueError("Presentation has no slides.")
    return slides[0]["objectId"]

def export_slide_as_jpeg(presentation_id, slide_object_id):
    # First, export as PNG (as Slides API only supports PNG for thumbnails)
    thumb = slides_svc.presentations().pages().getThumbnail(
        presentationId=presentation_id,
        pageObjectId=slide_object_id,
        thumbnailProperties_mimeType="PNG",
        thumbnailProperties_thumbnailSize="LARGE",
    ).execute()

    url = thumb.get("contentUrl")
    if not url:
        raise ValueError("No thumbnail URL returned by Slides API.")

    # Download with auth header
    headers = {"Authorization": f"Bearer {creds.token}"}
    r = requests.get(url, headers=headers)
    r.raise_for_status()
    png_bytes = r.content

    # Convert PNG bytes to JPEG bytes using Pillow
    img = PILImage.open(io.BytesIO(png_bytes))
    img_io = io.BytesIO()
    img.save(img_io, format='JPEG')
    jpeg_bytes = img_io.getvalue()
    return jpeg_bytes

def upload_file_to_folder(file_bytes, filename, mimetype, folder_id):
    media = MediaInMemoryUpload(file_bytes, mimetype=mimetype, resumable=False)
    meta = {"name": filename, "parents": [folder_id]}
    created = drive_svc.files().create(body=meta, media_body=media, fields="id, webViewLink").execute()
    return created["webViewLink"]

def check_file_exists(filename, folder_id):
    try:
        query = f"name = '{filename}' and '{folder_id}' in parents and trashed = false"
        response = drive_svc.files().list(q=query, spaces='drive', fields='files(id, webViewLink, name)').execute()
        files = response.get('files', [])
        if files:
            return files[0]
        return None
    except Exception as e:
        print(f"Error checking for existing file: {e}")
        return None

def create_poster_from_template(match, sequence_number):
    # Extract match date and format it as YYYYMMDD
    match_date_yyyy_mm_dd = match['matchDate'] # Already in YYYY-MM-DD format
    formatted_date = match_date_yyyy_mm_dd.replace('-', '') # YYYYMMDD format

    # New naming convention: YYYYMMMMDD_WeekX_L_TeamA_vs_TeamB
    week_num = match['week'].replace(' ', '')
    copy_name = f"{formatted_date}_{week_num}_{match['line']}_{match['teamAName']}_vs_{match['teamBName']}"

    # Construct the 'old' filename without the date prefix for cleanup
    old_copy_name_base = f"{week_num}_{match['line']}_{match['teamAName']}_vs_{match['teamBName']}"
    existing_old_file_info = check_file_exists(f"{old_copy_name_base}.jpeg", OUTPUT_FOLDER_ID)
    if existing_old_file_info:
        file_id = existing_old_file_info['id']
        file_name = existing_old_file_info['name']
        print(f"Existing old-named poster found: {file_name} (ID: {file_id}). Deleting...")
        try:
            drive_svc.files().delete(fileId=file_id).execute()
            print(f"Successfully deleted existing old-named poster: {file_name}")
        except HttpError as e:
            print(f"Error deleting existing old-named poster {file_name}: {e}")

    # Check if poster already exists (this checks for the new, date-prefixed name)
    existing_file_info = check_file_exists(f"{copy_name}.jpeg", OUTPUT_FOLDER_ID)
    if existing_file_info:
        file_id = existing_file_info['id']
        file_name = existing_file_info['name']
        print(f"Existing poster found: {file_name} (ID: {file_id}). Deleting...")
        try:
            drive_svc.files().delete(fileId=file_id).execute()
            print(f"Successfully deleted existing poster: {file_name}")
        except HttpError as e:
            print(f"Error deleting existing poster {file_name}: {e}")

    pres_id = copy_drive_file(TEMPLATE_PRESENTATION_ID, copy_name, OUTPUT_FOLDER_ID)

    left_players  = f"{match['teamAPlayer1']}\n&\n{match['teamAPlayer2']}".strip()
    right_players = f"{match['teamBPlayer1']}\n&\n{match['teamBPlayer2']}".strip()
    round_line = f"{match['week']} \u00b7 {match['line']}".strip(" \u00b7")

    replacements = {
        "{{TEAM_A}}": match["teamAName"],
        "{{TEAM_B}}": match["teamBName"],
        "{{ROUND_LINE}}": round_line,
        "{{LEFT_PLAYERS}}": left_players,
        "{{RIGHT_PLAYERS}}": right_players,
        "{{DATETIME}}": match["formattedDateTime"],
        "{{VENUE}}": match["venue"],
        "{{ADDRESS}}": match["address"],
    }

    batch_replace_text(pres_id, replacements)

    slide_id = get_first_slide_object_id(pres_id)
    jpeg_bytes = export_slide_as_jpeg(pres_id, slide_id) # Call the new JPEG export function

    link = upload_file_to_folder(jpeg_bytes, f"{copy_name}.jpeg", "image/jpeg", OUTPUT_FOLDER_ID)

    # Delete the temporary Google Slides presentation after JPEG is created
    try:
        drive_svc.files().delete(fileId=pres_id).execute()
        print(f"Deleted temporary presentation: {copy_name}")
    except HttpError as e:
        print(f"Error deleting temporary presentation {copy_name}: {e}")
    return link

# ---- RUN ----
all_matches = get_matches(SHEET_ID, SHEET_NAME)

# --- Temporarily setting a specific date for demonstration ---
# Set target_date_for_demonstration to None to use today's actual date
# target_date_for_demonstration = "2026-02-03" # Example: Set a specific past date to test older matches
# target_date_for_demonstration = "2026-02-16" # Example: Set a specific future date
upcoming_matches = get_upcoming_matches(all_matches) # Updated function call

print(f"Total matches read: {len(all_matches)}")
print(f"Upcoming matches (from today onwards): {len(upcoming_matches)} (TZ={LOCAL_TZ})")

if not upcoming_matches:
    print(f"No upcoming matches scheduled from today's date.")
else:
    for i, match in enumerate(upcoming_matches, start=1):
        try:
            url = create_poster_from_template(match, i)
            print(f"[{i}] {match['teamAName']} vs {match['teamBName']} -> {url}")
        except HttpError as e:
            print(f"[{i}] Google API error: {e}")
        except Exception as e:
            print(f"[{i}] Error: {e}")

# Regenerate all_matches and upcoming_matches using the updated format_datetime_for_poster
all_matches = get_matches(SHEET_ID, SHEET_NAME)
upcoming_matches = get_upcoming_matches(all_matches)

# Display the formattedDateTime for the first upcoming match
if upcoming_matches:
    print(upcoming_matches[0]['formattedDateTime'])
else:
    print("No upcoming matches available.")

if upcoming_matches:
    print(upcoming_matches[0]['formattedDateTime'])
else:
    print("No upcoming matches available.")